#!/usr/bin/env python3
#
# Copyright (C) 2026 Dan Brown
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

sys.path.insert(0, os.path.join(os.environ["AGENT_INSTALL_DIR"], "pypkg"))
from automx import state

data = json.load(sys.stdin) or {}

settings = state.load_settings()
settings.update({k: v for k, v in data.items() if k in state.DEFAULT_SETTINGS})
state.save_settings(settings)
