#!/usr/bin/env python3
#
# Copyright (C) 2026 Dan Brown
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

sys.path.insert(0, os.path.join(os.environ["AGENT_INSTALL_DIR"], "pypkg"))

import agent
from automx import dnshelperclient, mail, state

settings = state.load_settings()
domains = state.load_domains()

rdb = agent.redis_connect(use_replica=True)
try:
    _module_id, mail_hostname, user_domain_name, _domain_names = mail.get_instance_info(rdb)
except (mail.MailNotFound, mail.MailNotConfigured):
    mail_hostname = None
    user_domain_name = None

json.dump(
    {
        "service_host": settings["service_host"],
        "http2https": settings["http2https"],
        "display_names": settings["display_names"],
        "enabled_domain_count": sum(1 for flags in domains.values() if flags.get("enabled")),
        "mail_hostname": mail_hostname,
        "user_domain": user_domain_name,
        "dnshelper_present": dnshelperclient.find_instance() is not None,
    },
    fp=sys.stdout,
)
