#!/usr/bin/env python3
#
# Copyright (C) 2026 Dan Brown
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

sys.path.insert(0, os.path.join(os.environ["AGENT_INSTALL_DIR"], "pypkg"))

import agent
from automx import dnshelperclient, dnsstatus, node, state

data = json.load(sys.stdin) or {}

domains_state = state.load_domains()

if "domain" in data:
    agent.assert_exp(data["domain"] in domains_state, f"unknown domain {data['domain']}")
    target_domains = [data["domain"]]
else:
    target_domains = sorted(domains_state.keys())

settings = state.load_settings()
target_fqdn = settings.get("service_host") or node.get_node_fqdn()
dnshelper_target = dnshelperclient.find_instance()

results = [
    {"domain": domain, "dns": dnsstatus.domain_dns_status(domain, target_fqdn, dnshelper_target)}
    for domain in target_domains
]

json.dump({"results": results}, fp=sys.stdout)
